<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '2.3.2';
$moduleRevision = '8543373d243814c7a66becd000875b1758f7d50d';
$moduleWikiUrl = 'https://www.rstudio.net';